# Generated by Django 6.1 on 2026-08-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='name',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='color',
            field=models.CharField(default='black', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], default='spring', max_length=20),
            preserve_default=False,
        ),
    ]
