# Generated by Django 6.1 on 2026-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_remove_clothingitem_name_clothingitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
