# Generated by Django 6.1 on 2026-08-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0004_outfit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('pants', 'Pants'), ('shorts', 'Shorts'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear'), ('accessory', 'Accessory')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='season',
            field=models.CharField(max_length=100),
        ),
    ]
