# Generated by Django 6.1 on 2026-08-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_alter_clothingitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
