# Generated by Django 6.1 on 2026-09-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0006_clothingitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='accessory_type',
            field=models.CharField(
                blank=True,
                default='',
                max_length=20,
                choices=[
                    ('watch', 'Watch'),
                    ('sunglasses', 'Sunglasses'),
                    ('eyewear', 'Eyewear'),
                    ('bag', 'Bag'),
                    ('belt', 'Belt'),
                    ('hat', 'Hat'),
                    ('scarf', 'Scarf'),
                    ('tie', 'Tie'),
                    ('jewelry', 'Jewelry'),
                    ('other', 'Other'),
                ],
            ),
        ),
    ]
